[package]
name = "kernel-5_15"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[package.metadata.build-package]
variant-sensitive = "platform"
package-name = "kernel-5.15"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
# Use latest-srpm-url.sh to get this.
url = "https://cdn.amazonlinux.com/blobstore/e281307f83b2add956c002192425c943cdac6a4a2c2b201594dc8590ef68b26e/kernel-5.15.79-51.138.amzn2.src.rpm"
sha512 = "4ab89281ede2773f29e76f8c7fe50cb3b1a5b8819d8760dea2191ee6230ab32c7795485c36b302220560b18fe421edea1f55b0c4f266b39293d459b7b35e7676"

[build-dependencies]
microcode = { path = "../microcode" }
kpatch-build = { path = "../kpatch-build" }
